export enum ErrorTypeEnum {
  INVALID_JWT_TOKEN = 'INVALID_JWT_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_TAKEN = 'EMAIL_ALREADY_TAKEN',
  PASSWORD_IS_NOT_CORRECT = 'PASSWORD_IS_NOT_CORRECT',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
}
