import { Pattern } from './pattern';
import { PatternType } from './pattern-interface';
import { STANDARD_VAR_NAMES } from '../shared/standard-var-names';
import { initialDate } from '../shared/initial-date';
import { CUCUMBER } from '../framework/standard-frameworks';

/**
 * Built-in patterns
*/
/* eslint-disable*/
export const STANDARD_PATTERNS: Pattern[] = [
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given closed all but the first tab",
    "Given I have closed all but the first tab",
    "5fa19dd690f43c0001f00001",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given closed all but the first window",
    "Given I have closed all but the first window",
    "5fa19dd690f43c0001f00002",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given screen size is ${x} by ${y} pixels",
    "Given I have a screen that is ${x} by ${y} pixels",
    "5fa19dd690f43c0001f00003",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given there is no element on the page",
    "Given there is no element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" on the page",
    "5fa19dd690f43c0001f00004",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given there is an element on the page",
    "Given there is an element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" on the page",
    "5fa19dd690f43c0001f00005",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given prompt is not opened",
    "Given a prompt is not opened",
    "5fa19dd690f43c0001f00006",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given prompt is opened",
    "Given a prompt is opened",
    "5fa19dd690f43c0001f00007",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given confirmbox is not opened",
    "Given a confirmbox is not opened",
    "5fa19dd690f43c0001f00008",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given confirmbox is opened",
    "Given a confirmbox is opened",
    "5fa19dd690f43c0001f00009",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given alertbox is not opened",
    "Given a alertbox is not opened",
    "5fa19dd690f43c0001f00010",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given alertbox is opened",
    "Given a alertbox is opened",
    "5fa19dd690f43c0001f00011",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is not positioned at \"n\" px on the y axis",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not positioned at ${px}px on the y axis",
    "5fa19dd690f43c0001f00012",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is positioned at \"n\" px on the y axis",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is positioned at ${px}px on the y axis",
    "5fa19dd690f43c0001f00013",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is not positioned at \"n\" px on the x axis",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not positioned at ${px}px on the x axis",
    "5fa19dd690f43c0001f00014",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is positioned at \"n\" px on the x axis",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is positioned at ${px}px on the x axis",
    "5fa19dd690f43c0001f00015",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element dimension is not \"n\" px tall",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not ${px}px tall",
    "5fa19dd690f43c0001f00016",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element dimension is \"n\" px tall",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is ${px}px tall",
    "5fa19dd690f43c0001f00017",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element dimension is not \"n\" px broad",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not ${px}px broad",
    "5fa19dd690f43c0001f00018",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element dimension is \"n\" px broad",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is ${px}px broad",
    "5fa19dd690f43c0001f00019",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given cookie not exists",
    "Given the cookie \"${cookieName}\" does not exist",
    "5fa19dd690f43c0001f00020",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given cookie exists",
    "Given the cookie \"${cookieName}\" does exist",
    "5fa19dd690f43c0001f00021",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given cookie not contains",
    "Given the cookie \"${cookieName}\" contains not the value \"${expectedValue}\"",
    "5fa19dd690f43c0001f00022",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given cookie contains",
    "Given the cookie \"${cookieName}\" contains the value \"${expectedValue}\"",
    "5fa19dd690f43c0001f00023",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given css attribute is not equal",
    "Given the css attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not \"${expectedValue}\"",
    "5fa19dd690f43c0001f00024",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given css attribute is equal",
    "Given the css attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is \"${expectedValue}\"",
    "5fa19dd690f43c0001f00025",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given attribute is not equal",
    "Given the attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not \"${expectedValue}\"",
    "5fa19dd690f43c0001f00026",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given attribute is equal",
    "Given the attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is \"${expectedValue}\"",
    "5fa19dd690f43c0001f00027",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given url is not equal",
    "Given the page url is not \"${url}\"",
    "5fa19dd690f43c0001f00028",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given url is equal",
    "Given the page url is \"${url}\"",
    "5fa19dd690f43c0001f00029",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is not empty",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not empty",
    "5fa19dd690f43c0001f00030",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button is not empty",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not empty",
    "5fa19dd690f43c0001f00031",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is empty",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is empty",
    "5fa19dd690f43c0001f00032",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button is empty",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is empty",
    "5fa19dd690f43c0001f00033",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element not contains any text",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains any text",
    "5fa19dd690f43c0001f00034",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button not contains any text",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains any text",
    "5fa19dd690f43c0001f00035",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element contains any text",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains any text",
    "5fa19dd690f43c0001f00036",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button contains any text",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains any text",
    "5fa19dd690f43c0001f00037",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element not contains the text",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the text \"{text}\"",
    "5fa19dd690f43c0001f00038",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button not contains the text",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the text \"{text}\"",
    "5fa19dd690f43c0001f00039",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given container not contains the text",
    "Given the container \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the text \"{text}\"",
    "5fa19dd690f43c0001f00040",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element contains the text",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the text \"{text}\"",
    "5fa19dd690f43c0001f00041",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button contains the text",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the text \"{text}\"",
    "5fa19dd690f43c0001f00042",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given container contains the text",
    "Given the container \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the text \"{text}\"",
    "5fa19dd690f43c0001f00043",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element not matches the text",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not matches the text \"${text}\"",
    "5fa19dd690f43c0001f00044",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element matches the text",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" matches the text \"${text}\"",
    "5fa19dd690f43c0001f00045",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button not matches the text",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not matches the text \"${text}\"",
    "5fa19dd690f43c0001f00046",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given button matches the text",
    "Given the button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" matches the text \"${text}\"",
    "5fa19dd690f43c0001f00047",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element contains not the same text as element",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains not the same text as element \"${element2Css}\"",
    "5fa19dd690f43c0001f00048",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element contains the same text as element",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the same text as element \"${element2Css}\"",
    "5fa19dd690f43c0001f00049",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given title is not equal",
    "Given the title is not \"${text}\"",
    "5fa19dd690f43c0001f00050",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given title is equal",
    "Given the title is \"${text}\"",
    "5fa19dd690f43c0001f00051",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given checkbox is not checked",
    "Given the checkbox \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not checked",
    "5fa19dd690f43c0001f00052",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given checkbox is checked",
    "Given the checkbox \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is checked",
    "5fa19dd690f43c0001f00053",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is not selected",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not selected",
    "5fa19dd690f43c0001f00054",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is selected",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is selected",
    "5fa19dd690f43c0001f00055",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is not enabled",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not enabled",
    "5fa19dd690f43c0001f00056",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is enabled",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is enabled",
    "5fa19dd690f43c0001f00057",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is not displayed",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not displayed",
    "5fa19dd690f43c0001f00058",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given element is displayed",
    "Given the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is displayed",
    "5fa19dd690f43c0001f00059",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given open site",
    "Given I open the site \"${url}\"",
    "5fa19dd690f43c0001f00060",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "given open url",
    "Given I open the url \"${url}\"",
    "5fa19dd690f43c0001f00061",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect prompt not contains the text",
    "Then I expect that a prompt not contains the text \"${text}\"",
    "5fa19dd690f43c0001f00062",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect prompt contains the text",
    "Then I expect that a prompt contains the text \"${text}\"",
    "5fa19dd690f43c0001f00063",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect confirmbox not contains the text",
    "Then I expect that a confirmbox not contains the text \"${text}\"",
    "5fa19dd690f43c0001f00064",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect confirmbox contains the text",
    "Then I expect that a confirmbox contains the text \"${text}\"",
    "5fa19dd690f43c0001f00065",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect alertbox not contains the text",
    "Then I expect that a alertbox not contains the text \"${text}\"",
    "5fa19dd690f43c0001f00066",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect alertbox contains the text",
    "Then I expect that a alertbox contains the text \"${text}\"",
    "5fa19dd690f43c0001f00067",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect prompt is not opened",
    "Then I expect that a prompt is not opened",
    "5fa19dd690f43c0001f00068",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect prompt is opened",
    "Then I expect that a prompt is opened",
    "5fa19dd690f43c0001f00069",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect confirmbox is not opened",
    "Then I expect that a confirmbox is not opened",
    "5fa19dd690f43c0001f00070",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect confirmbox is opened",
    "Then I expect that a confirmbox is opened",
    "5fa19dd690f43c0001f00071",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect alertbox is not opened",
    "Then I expect that a alertbox is not opened",
    "5fa19dd690f43c0001f00072",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect alertbox is opened",
    "Then I expect that a alertbox is opened",
    "5fa19dd690f43c0001f00073",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to be checked",
    "Then I wait on element to be checked",
    "5fa19dd690f43c0001f00074",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to be enabled",
    "Then I wait on element to be enabled",
    "5fa19dd690f43c0001f00075",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to be selected",
    "Then I wait on element to be selected",
    "5fa19dd690f43c0001f00076",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to be displayed",
    "Then I wait on element to be displayed",
    "5fa19dd690f43c0001f00077",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to contain a text",
    "Then I wait on element to contain a text \"${text}\"",
    "5fa19dd690f43c0001f00078",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to contain a value",
    "Then I wait on element to contain a value \"${value}\"",
    "5fa19dd690f43c0001f00079",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element to exist",
    "Then I wait on element to exist",
    "5fa19dd690f43c0001f00080",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to be checked",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to be checked",
    "5fa19dd690f43c0001f00081",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to be enabled",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to be enabled",
    "5fa19dd690f43c0001f00082",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to be selected",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to be selected",
    "5fa19dd690f43c0001f00083",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to be displayed",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to be displayed",
    "5fa19dd690f43c0001f00084",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to contain a text",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to contain a text \"${text}\"",
    "5fa19dd690f43c0001f00085",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to contain a value",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to contain a value \"${value}\"",
    "5fa19dd690f43c0001f00086",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms to exist",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms to exist",
    "5fa19dd690f43c0001f00087",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element for \"n\" ms",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" for ${ms}ms",
    "5fa19dd690f43c0001f00088",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "wait on element",
    "Then I wait on element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00089",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not focused",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not focused",
    "5fa19dd690f43c0001f00090",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is focused",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is focused",
    "5fa19dd690f43c0001f00091",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url is opened in a new window",
    "Then I expect the url \"${url}\" is opened in a new window",
    "5fa19dd690f43c0001f00092",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url is opened in a new tab",
    "Then I expect the url \"${url}\" is opened in a new tab",
    "5fa19dd690f43c0001f00093",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect new tab has not been opened",
    "Then I expect a new tab has not been opened",
    "5fa19dd690f43c0001f00094",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect new tab has been opened",
    "Then I expect a new tab has been opened",
    "5fa19dd690f43c0001f00095",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect new window has not been opened",
    "Then I expect a new window has not been opened",
    "5fa19dd690f43c0001f00096",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect new window has been opened",
    "Then I expect a new window has been opened",
    "5fa19dd690f43c0001f00097",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element does not have the class",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" does not have the class \"${expectedClassName}\"",
    "5fa19dd690f43c0001f00098",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element has the class",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" has the class \"${expectedClassName}\"",
    "5fa19dd690f43c0001f00099",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not positioned at \"n\" px on the y axis",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not positioned at ${px}px on the y axis",
    "5fa19dd690f43c0001f00100",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is positioned at \"n\" px on the y axis",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is positioned at ${px}px on the y axis",
    "5fa19dd690f43c0001f00101",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not positioned at \"n\" px on the x axis",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not positioned at ${px}px on the x axis",
    "5fa19dd690f43c0001f00102",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is positioned at \"n\" px on the x axis",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is positioned at ${px}px on the x axis",
    "5fa19dd690f43c0001f00103",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element dimension is not \"n\" px tall",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not ${px}px tall",
    "5fa19dd690f43c0001f00104",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element dimension is \"n\" px tall",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is ${px}px tall",
    "5fa19dd690f43c0001f00105",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element dimension is not \"n\" px broad",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not ${px}px broad",
    "5fa19dd690f43c0001f00106",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element dimension is \"n\" px broad",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is ${px}px broad",
    "5fa19dd690f43c0001f00107",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect cookie not exists",
    "Then I expect that cookie \"${cookieName}\" not exists",
    "5fa19dd690f43c0001f00108",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect cookie exists",
    "Then I expect that cookie \"${cookieName}\" exists",
    "5fa19dd690f43c0001f00109",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect cookie not contains",
    "Then I expect that cookie \"${cookieName}\" not contains \"${expectedValue}\"",
    "5fa19dd690f43c0001f00110",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect cookie contains",
    "Then I expect that cookie \"${cookieName}\" contains \"${expectedValue}\"",
    "5fa19dd690f43c0001f00111",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not enabled",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not enabled",
    "5fa19dd690f43c0001f00112",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is enabled",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is enabled",
    "5fa19dd690f43c0001f00113",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not selected",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not selected",
    "5fa19dd690f43c0001f00114",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is selected",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is selected",
    "5fa19dd690f43c0001f00115",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect checkbox is not checked",
    "Then I expect that checkbox \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not checked",
    "5fa19dd690f43c0001f00116",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect checkbox is checked",
    "Then I expect that checkbox \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is checked",
    "5fa19dd690f43c0001f00117",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect font css attribute is not equal",
    "Then I expect that the font css attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not \"${expectedValue}\"",
    "5fa19dd690f43c0001f00118",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect font css attribute is equal",
    "Then I expect that the font css attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is \"${expectedValue}\"",
    "5fa19dd690f43c0001f00119",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect font attribute is not equal",
    "Then I expect that the font attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not \"${expectedValue}\"",
    "5fa19dd690f43c0001f00120",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect font attribute is equal",
    "Then I expect that the font attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is \"${expectedValue}\"",
    "5fa19dd690f43c0001f00121",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect css attribute is not equal",
    "Then I expect that the css attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not \"${expectedValue}\"",
    "5fa19dd690f43c0001f00122",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect css attribute is equal",
    "Then I expect that the css attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is \"${expectedValue}\"",
    "5fa19dd690f43c0001f00123",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect attribute is not equal",
    "Then I expect that the attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not \"${expectedValue}\"",
    "5fa19dd690f43c0001f00124",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect attribute is equal",
    "Then I expect that the attribute \"${attrName}\" from element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is \"${expectedValue}\"",
    "5fa19dd690f43c0001f00125",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url not contains",
    "Then I expect the url to not contain \"${url}\"",
    "5fa19dd690f43c0001f00126",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url contains",
    "Then I expect the url to contain \"${url}\"",
    "5fa19dd690f43c0001f00127",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url path is not equal",
    "Then I expect that the path is not \"${path}\"",
    "5fa19dd690f43c0001f00128",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url path is equal",
    "Then I expect that the path is \"${path}\"",
    "5fa19dd690f43c0001f00129",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url is not equal",
    "Then I expect that the url is not \"${url}\"",
    "5fa19dd690f43c0001f00130",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect url is equal",
    "Then I expect that the url is \"${url}\"",
    "5fa19dd690f43c0001f00131",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not empty",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not empty",
    "5fa19dd690f43c0001f00132",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button is not empty",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not empty",
    "5fa19dd690f43c0001f00133",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is empty",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is empty",
    "5fa19dd690f43c0001f00134",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button is empty",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is empty",
    "5fa19dd690f43c0001f00135",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element not contains any text",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains any text",
    "5fa19dd690f43c0001f00136",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button not contains any text",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains any text",
    "5fa19dd690f43c0001f00137",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element contains any text",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains any text",
    "5fa19dd690f43c0001f00138",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button contains any text",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains any text",
    "5fa19dd690f43c0001f00139",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element not contains the text",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the text \"{text}\"",
    "5fa19dd690f43c0001f00140",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button not contains the text",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the text \"{text}\"",
    "5fa19dd690f43c0001f00141",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect container not contains the text",
    "Then I expect that container \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the text \"{text}\"",
    "5fa19dd690f43c0001f00142",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element contains the text",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the text \"{text}\"",
    "5fa19dd690f43c0001f00143",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button contains the text",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the text \"{text}\"",
    "5fa19dd690f43c0001f00144",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect container contains the text",
    "Then I expect that container \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the text \"{text}\"",
    "5fa19dd690f43c0001f00145",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element not matches the text",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not matches the text \"${text}\"",
    "5fa19dd690f43c0001f00146",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element matches the text",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" matches the text \"${text}\"",
    "5fa19dd690f43c0001f00147",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button not matches the text",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not matches the text \"${text}\"",
    "5fa19dd690f43c0001f00148",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect button matches the text",
    "Then I expect that button \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" matches the text \"${text}\"",
    "5fa19dd690f43c0001f00149",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element not contains the same text as element",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" not contains the same text as element \"${element2Css}\"",
    "5fa19dd690f43c0001f00150",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element contains the same text as element",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" contains the same text as element \"${element2Css}\"",
    "5fa19dd690f43c0001f00151",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element does not exist",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" does not exist",
    "5fa19dd690f43c0001f00152",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element does exist",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" does exist",
    "5fa19dd690f43c0001f00153",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not within the viewport",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not within the viewport",
    "5fa19dd690f43c0001f00154",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is within the viewport",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is within the viewport",
    "5fa19dd690f43c0001f00155",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element becomes not displayed",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" becomes not displayed",
    "5fa19dd690f43c0001f00156",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element becomes displayed",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" becomes displayed",
    "5fa19dd690f43c0001f00157",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is not displayed",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is not displayed",
    "5fa19dd690f43c0001f00158",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element is displayed",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" is displayed",
    "5fa19dd690f43c0001f00159",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element does not appear exactly \"n\" times",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" does not appear exactly \"${n}\" times",
    "5fa19dd690f43c0001f00160",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect element does appear exactly \"n\" times",
    "Then I expect that element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" does appear exactly \"${n}\" times",
    "5fa19dd690f43c0001f00161",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect title not contains",
    "Then I expect that the title not contains \"${text}\"",
    "5fa19dd690f43c0001f00162",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect title contains",
    "Then I expect that the title contains \"${text}\"",
    "5fa19dd690f43c0001f00163",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect title is not equal",
    "Then I expect that the title is not \"${text}\"",
    "5fa19dd690f43c0001f00164",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "expect title is equal",
    "Then I expect that the title is \"${text}\"",
    "5fa19dd690f43c0001f00165",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "move to element with an offset",
    "When I move to element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" with an offset of ${x},${y}",
    "5fa19dd690f43c0001f00166",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "move to element",
    "When I move to element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00167",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "select option with text for element",
    "When I select the option with the text \"${text}\" for element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00168",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "select option with value for element",
    "When I select the option with the value \"${value}\" for element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00169",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "select option with name for element",
    "When I select the option with the name \"${name}\" for element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00170",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "select option by index for element",
    "When I select the \"${index}\" option for element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00171",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "focus last opened window",
    "When I focus the last opened window",
    "5fa19dd690f43c0001f00172",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "focus last opened tab",
    "When I focus the last opened tab",
    "5fa19dd690f43c0001f00173",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "close last opened window",
    "When I close the last opened window",
    "5fa19dd690f43c0001f00174",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "close last opened tab",
    "When I close the last opened tab",
    "5fa19dd690f43c0001f00175",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "scroll to element",
    "When I scroll to element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00176",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "set prompt text",
    "When I enter \"${text}\" into the prompt",
    "5fa19dd690f43c0001f00177",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "accept alertbox",
    "When I accept the alertbox",
    "5fa19dd690f43c0001f00178",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "accept confirmbox",
    "When I accept the confirmbox",
    "5fa19dd690f43c0001f00179",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "accept prompt",
    "When I accept the prompt",
    "5fa19dd690f43c0001f00180",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "dismiss prompt",
    "When I dismiss the prompt",
    "5fa19dd690f43c0001f00181",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "dismiss confirmbox",
    "When I dismiss the confirmbox",
    "5fa19dd690f43c0001f00182",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "dismiss alertbox",
    "When I dismiss the alertbox",
    "5fa19dd690f43c0001f00183",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "press key",
    "When I press \"${key}\"",
    "5fa19dd690f43c0001f00184",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "delete cookies",
    "When I delete the cookie \"${cookieName}\"",
    "5fa19dd690f43c0001f00185",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "set cookie",
    "When I set a cookie \"${cookieName}\" with the content \"${cookieContent}\"",
    "5fa19dd690f43c0001f00186",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "pause",
    "When I pause for ${ms}ms",
    "5fa19dd690f43c0001f00187",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "drag element",
    "When I drag element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\" to element \"${" + STANDARD_VAR_NAMES.PARENT_ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00188",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "clear",
    "When I clear the inputfield \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00189",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "set input text",
    "When I set \"${text}\" to the inputfield \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00190",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "add input text",
    "When I add \"${text}\" to the inputfield \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00191",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "click",
    "When I click on the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00192",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "click link",
    "When I click on the link \"${link}\"",
    "5fa19dd690f43c0001f00193",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "doubleclick",
    "When I doubleclick on the element \"${" + STANDARD_VAR_NAMES.ELEMENT_CSS + "}\"",
    "5fa19dd690f43c0001f00194",
    initialDate,
  ),
  new Pattern(
    PatternType.ACTION,
    CUCUMBER,
    "doubleclick link",
    "When I doubleclick on the link \"${link}\"",
    "5fa19dd690f43c0001f00195",
    initialDate,
  ),
];
/* eslint-enable*/

/**
 * default is 'wdio.byCss'
*/
export const DEFAULT_PO_PATTERN = STANDARD_PATTERNS.filter(pt => pt.type === PatternType.PAGE_OBJECT)[0]?.id || null;
